language: python
python:
- 2.7
- 3.6
install:
- pip install tox-travis
- pip install pytest-cov coveralls
script: tox
after_success:
    - if [[ $ENV == python=3.* ]]; then
          coveralls;
      fi
